spring:
  application:
    name: user-service

server:
  port: 8002
  servlet:
    context-path: /user-service

redis:
  host: 127.0.0.1
  port: 6379
  password:

redisson:
  address: redis://127.0.0.1:6379
  password:

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true

logging:
  level:
    com.wongcu: debug

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000