spring:
  application:
    name: user-service
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
        url: jdbc:mysql://localhost:3306/kuibu_user?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x' from dual
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        maxOpenPreparedStatements: 20

server:
  port: 8002
  servlet:
    context-path: /user-service

redis:
  host: 127.0.0.1
  port: 6379
  password:

redisson:
  address: redis://127.0.0.1:6379
  password:

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true

logging:
  level:
    com.wongcu: debug

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

mybatis:
  typeAliasesPackage: com.wongcu.**.orm.entity
  mapperLocations: classpath:com/wongcu/**/orm/mapper/*.xml